apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: us.gcr.io/make-a-devops-k8s/go-k8s-demo
    workspace: .
  local: {}
deploy:
  kubectl:
    manifests:
      - ./k8s/dev/*
