apiVersion: v1
kind: Service
metadata:
  name: go-k8s-demo
  labels:
    app: go-k8s-demo
spec:
  type: NodePort
  ports:
    - port: 1337
      targetPort: 1337
      protocol: TCP
      name: go-k8s-demo
  selector:
    app: go-k8s-demo
